import icons from "./icons";

export const typeIcons = {
  normal: icons.normalIcon,
  grass: icons.grassIcon,
  fire: icons.fireIcon,
  water: icons.waterIcon,
  flying: icons.flyingIcon,
  fighting: icons.fightingIcon,
  poison: icons.poisonIcon,
  electric: icons.electricIcon,
  ground: icons.groundIcon,
  psychic: icons.psychicIcon,
  ice: icons.iceIcon,
  bug: icons.bugIcon,
  ghost: icons.ghostIcon,
  steel: icons.steelIcon,
  dragon: icons.dragonIcon,
  dark: icons.darkIcon,
  fairy: icons.fairyIcon,
  rock: icons.rockIcon,
};
export const typeColors = {
  normal: "#919AA2",
  grass: "#63BC5B",
  fire: "#FF9D53",
  water: "#4C91D6",
  flying: "#4A677B",
  fighting: "#CF3E69",
  poison: "#AC6AC9",
  electric: "#F3D338",
  ground: "#DA7844",
  psychic: "#F97277",
  ice: "#75CFC1",
  bug: "#91C228",
  ghost: "#5169AE",
  steel: "#5F756D",
  dragon: "#036DC5",
  dark: "#5A5266",
  fairy: "#ED90E7",
  rock: "#C8B88C",
};
